import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "next-themes";
import { Header } from "@/components/layouts/header";
import { Footer } from "@/components/app-ui/Footer";

// const inter = Inter({ subsets: ["latin"] });

const inter = localFont({
  src: [
    {
      path: "../../public/fonts/Inter-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Inter-SemiBold.otf",
      weight: "600",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("bg-background text-foreground", inter.className)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="mx-auto flex min-h-screen max-w-[60rem] flex-col gap-12 p-8 @container/main">
            <Header />
            {children}
            <hr className="mt-auto peer-[[href]]:mt-0" />
            {/* <Newsletter
              title='Newsletter'
              description='Get updates on new tools, alternatives, and other cool stuff.'
            /> */}
            <Footer />
          </div>
        </ThemeProvider>
        {/* <ScrollRestoration /> */}
      </body>
    </html>
  );
}
